### ISSUE TITLE
week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [Kuanlinhack/git-practice#1]
作業整體正確。

如同昨天在課堂上的分享，從現在開始練習更深入地去探索一個技術，訓練自己去多問一點問題，有更多的好奇心一點。

觀察紀錄這邊，可以透過複製或截圖，確實地把看到的東西紀錄起來，可以參考課堂上分享的其他同學的成果，練習讓自己的報告更完整，這些將來都會是你累積的作品。

**Comment by Kuanlinhack** [comment]
好的 了解！ 謝謝老師

**Comment by azole** [comment]
謝謝你的回覆，這個 issue 可以 close 了。

**Comment by Kuanlinhack** [comment]
好的！
